# Generated by Django 3.2.3 on 2022-01-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bakery',
            fields=[
                ('bakery_name', models.CharField(max_length=50)),
                ('bakery_mrp', models.IntegerField()),
                ('bakery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bakery_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dairy',
            fields=[
                ('dairy_name', models.CharField(max_length=50)),
                ('dairy_mrp', models.IntegerField()),
                ('dairy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dairy_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='electrical',
            fields=[
                ('electrical_name', models.CharField(max_length=50)),
                ('electrical_mrp', models.IntegerField()),
                ('electrical_id', models.IntegerField(primary_key=True, serialize=False)),
                ('electrical_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='grocery',
            fields=[
                ('grocery_name', models.CharField(max_length=50)),
                ('grocery_mrp', models.IntegerField()),
                ('grocery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grocery_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stationary',
            fields=[
                ('stationary_name', models.CharField(max_length=50)),
                ('stationary_mrp', models.IntegerField()),
                ('stationary_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stationary_price', models.IntegerField()),
            ],
        ),
    ]
