# Generated by Django 3.2.3 on 2022-01-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bakery_dairy_electrical_grocery_stationary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('fruits_name', models.CharField(max_length=50)),
                ('fruits_mrp', models.IntegerField()),
                ('fruits_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fruits_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('vegetables_name', models.CharField(max_length=50)),
                ('vegetables_mrp', models.IntegerField()),
                ('vegetables_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vegetables_price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
