# Generated by Django 3.2.3 on 2022-01-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220102_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fruits',
            new_name='Fruit',
        ),
        migrations.RenameModel(
            old_name='Vegetables',
            new_name='Vegetable',
        ),
    ]
